// /lib/locations.ts
export type Location = {
  slug: string
  city: string
  relatedPhrases?: string[]
  metaDescription?: string
}


export const locations: Location[] = [
  {
    slug: "3d-printen-in-aalst",
    city: "Aalst",
    relatedPhrases: [
      "3D print service Aalst",
      "rapid prototyping Aalst",
      "3D printing bedrijf Aalst",
      "3D printen nabij Aalst",
      "3D model laten printen Aalst",
    ],
    metaDescription: "Laat je 3D-idee werkelijkheid worden in Aalst van prototypes tot kleine series, PLA, PETG en TPU beschikbaar. Vraag een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-antwerpen",
    city: "Antwerpen",
    relatedPhrases: [
      "3D print service Antwerpen",
      "rapid prototyping Antwerpen",
      "3D printing bedrijf Antwerpen",
      "3D printen haven Antwerpen",
      "3D model laten printen Antwerpen",
    ],
    metaDescription:
      "Professionele 3D prints in Antwerpen voor havenbedrijven, creatieve bureaus en onderwijs. PLA, PETG en TPU met snelle levering.",
  },
  {
    slug: "3d-printen-in-herzele",
    city: "Herzele",
    relatedPhrases: [
      "3D print service Herzele",
      "rapid prototyping Herzele",
      "3D printing bedrijf Herzele",
      "3D printen nabij Herzele",
      "3D model laten printen Herzele",
    ],
    metaDescription: "X3DPrints verzorgt 3D prints voor Herzele en omgeving van prototypes tot kleine series, PLA, PETG en TPU beschikbaar. Upload je model bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-borsbeke",
    city: "Borsbeke",
    relatedPhrases: [
      "3D print service Borsbeke",
      "rapid prototyping Borsbeke",
      "3D printing bedrijf Borsbeke",
      "3D printen nabij Borsbeke",
      "3D model laten printen Borsbeke",
    ],
    metaDescription: "3D printservice in Borsbeke met focus op precisie van prototypes tot kleine series, PLA, PETG en TPU beschikbaar. X3DPrints helpt je project vooruit.",
  },
  {
    slug: "3d-printen-in-hillegem",
    city: "Hillegem",
    relatedPhrases: [
      "3D print service Hillegem",
      "rapid prototyping Hillegem",
      "3D printing bedrijf Hillegem",
      "3D printen nabij Hillegem",
      "3D model laten printen Hillegem",
    ],
    metaDescription: "Nauwkeurige 3D printing voor bedrijven en makers in Hillegem van prototypes tot kleine series, PLA, PETG en TPU beschikbaar. Ontvang je prijs bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-ressegem",
    city: "Ressegem",
    relatedPhrases: [
      "3D print service Ressegem",
      "rapid prototyping Ressegem",
      "3D printing bedrijf Ressegem",
      "3D printen nabij Ressegem",
      "3D model laten printen Ressegem",
    ],
    metaDescription: "Professionele 3D prints in Ressegem, snel geleverd van prototypes tot kleine series, PLA, PETG en TPU beschikbaar. X3DPrints print jouw ontwerp met zorg.",
  },
  {
    slug: "3d-printen-in-sint-antelinks",
    city: "Sint-Antelinks",
    relatedPhrases: [
      "3D print service Sint-Antelinks",
      "rapid prototyping Sint-Antelinks",
      "3D printing bedrijf Sint-Antelinks",
      "3D printen nabij Sint-Antelinks",
      "3D model laten printen Sint-Antelinks",
    ],
    metaDescription: "Laat je 3D-idee werkelijkheid worden in Sint-Antelinks voor prototypes, mallen en functionele onderdelen. Vraag een offerte bij X3DPrints. PLA, PETG.",
  },
  {
    slug: "3d-printen-in-sint-lievens-esse",
    city: "Sint-Lievens-Esse",
    relatedPhrases: [
      "3D print service Sint-Lievens-Esse",
      "rapid prototyping Sint-Lievens-Esse",
      "3D printing bedrijf Sint-Lievens-Esse",
      "3D printen nabij Sint-Lievens-Esse",
      "3D model laten printen Sint-Lievens-Esse",
    ],
    metaDescription: "X3DPrints verzorgt 3D prints voor Sint-Lievens-Esse en omgeving voor prototypes, mallen en functionele onderdelen. Upload je model bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-steenhuize-wijnhuize",
    city: "Steenhuize-Wijnhuize",
    relatedPhrases: [
      "3D print service Steenhuize-Wijnhuize",
      "rapid prototyping Steenhuize-Wijnhuize",
      "3D printing bedrijf Steenhuize-Wijnhuize",
      "3D printen nabij Steenhuize-Wijnhuize",
      "3D model laten printen Steenhuize-Wijnhuize",
    ],
    metaDescription: "3D printservice in Steenhuize-Wijnhuize met focus op precisie voor prototypes, mallen en functionele onderdelen. X3DPrints helpt je project vooruit.",
  },
  {
    slug: "3d-printen-in-woubrechtegem",
    city: "Woubrechtegem",
    relatedPhrases: [
      "3D print service Woubrechtegem",
      "rapid prototyping Woubrechtegem",
      "3D printing bedrijf Woubrechtegem",
      "3D printen nabij Woubrechtegem",
      "3D model laten printen Woubrechtegem",
    ],
    metaDescription: "Nauwkeurige 3D printing voor bedrijven en makers in Woubrechtegem voor prototypes, mallen en functionele onderdelen. Ontvang je prijs bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-geraardsbergen",
    city: "Geraardsbergen",
    relatedPhrases: [
      "3D print service Geraardsbergen",
      "rapid prototyping Geraardsbergen",
      "3D printing bedrijf Geraardsbergen",
      "3D printen nabij Geraardsbergen",
      "3D model laten printen Geraardsbergen",
    ],
    metaDescription: "Professionele 3D prints in Geraardsbergen voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-erpe-mere",
    city: "Erpe-mere",
    relatedPhrases: [
      "3D print service erpe-mere",
      "rapid prototyping erpe-mere",
      "3D printing bedrijf erpe-mere",
      "3D printen nabij erpe-mere",
      "3D model laten printen erpe-mere",
    ],
    metaDescription: "Professionele 3D prints in Erpe-mere voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-zottegem",
    city: "Zottegem",
    relatedPhrases: [
      "3D print service zottegem",
      "rapid prototyping zottegem",
      "3D printing bedrijf zottegem",
      "3D printen nabij zottegem",
      "3D model laten printen zottegem",
    ],
    metaDescription: "Professionele 3D prints in Zottegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-oudenaarde",
    city: "Oudenaarde",
    relatedPhrases: [
      "3D print service Oudenaarde",
      "rapid prototyping Oudenaarde",
      "3D printing bedrijf Oudenaarde",
      "3D printen nabij Oudenaarde",
      "3D model laten printen Oudenaarde",
    ],
    metaDescription: "Professionele 3D prints in Oudenaarde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-gentbrugge",
    city: "Gentbrugge",
    relatedPhrases: [
      "3D print service gentbrugge",
      "rapid prototyping gentbrugge",
      "3D printing bedrijf gentbrugge",
      "3D printen nabij gentbrugge",
      "3D model laten printen gentbrugge",
    ],
    metaDescription: "Professionele 3D prints in Gentbrugge voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-affligem",
    city: "Affligem",
    relatedPhrases: [
      "3D print service affligem",
      "rapid prototyping affligem",
      "3D printing bedrijf affligem",
      "3D printen nabij affligem",
      "3D model laten printen affligem",
    ],
    metaDescription: "Professionele 3D prints in Affligem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-dendermonde",
    city: "Dendermonde",
    relatedPhrases: [
      "3D print service dendermonde",
      "rapid prototyping dendermonde",
      "3D printing bedrijf dendermonde",
      "3D printen nabij dendermonde",
      "3D model laten printen dendermonde",
    ],
    metaDescription: "Professionele 3D prints in Dendermonde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-haaltert",
    city: "Haaltert",
    relatedPhrases: [
      "3D print service haaltert",
      "rapid prototyping haaltert",
      "3D printing bedrijf haaltert",
      "3D printen nabij haaltert",
      "3D model laten printen haaltert",
    ],
    metaDescription: "Professionele 3D prints in Haaltert voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-lede",
    city: "Lede",
    relatedPhrases: [
      "3D print service lede",
      "rapid prototyping lede",
      "3D printing bedrijf lede",
      "3D printen nabij lede",
      "3D model laten printen lede",
    ],
    metaDescription: "Professionele 3D prints in Lede voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-lierde",
    city: "Lierde",
    relatedPhrases: [
      "3D print service lierde",
      "rapid prototyping lierde",
      "3D printing bedrijf lierde",
      "3D printen nabij lierde",
      "3D model laten printen lierde",
    ],
    metaDescription: "Professionele 3D prints in Lierde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-merelbeke",
    city: "Merelbeke",
    relatedPhrases: [
      "3D print service merelbeke",
      "rapid prototyping merelbeke",
      "3D printing bedrijf merelbeke",
      "3D printen nabij merelbeke",
      "3D model laten printen merelbeke",
    ],
    metaDescription: "Professionele 3D prints in Merelbeke voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-lievens-houtem",
    city: "Sint-Lievens-Houtem",
    relatedPhrases: [
      "3D print service sint-lievens-houtem",
      "rapid prototyping sint-lievens-houtem",
      "3D printing bedrijf sint-lievens-houtem",
      "3D printen nabij sint-lievens-houtem",
      "3D model laten printen sint-lievens-houtem",
    ],
    metaDescription: "Professionele 3D prints in Sint-Lievens-Houtem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-wetteren",
    city: "Wetteren",
    relatedPhrases: [
      "3D print service wetteren",
      "rapid prototyping wetteren",
      "3D printing bedrijf wetteren",
      "3D printen nabij wetteren",
      "3D model laten printen wetteren",
    ],
    metaDescription: "Professionele 3D prints in Wetteren voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-brakel",
    city: "Brakel",
    relatedPhrases: [
      "3D print service brakel",
      "rapid prototyping brakel",
      "3D printing bedrijf brakel",
      "3D printen nabij brakel",
      "3D model laten printen brakel",
    ],
    metaDescription: "Professionele 3D prints in Brakel voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-gent",
    city: "Gent",
    relatedPhrases: [
      "3D print service gent",
      "rapid prototyping gent",
      "3D printing bedrijf gent",
      "3D printen nabij gent",
      "3D model laten printen gent",
    ],
    metaDescription: "Professionele 3D prints in Gent voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-erwetegem",
    city: "Erwetegem",
    relatedPhrases: [
      "3D print service erwetegem",
      "rapid prototyping erwetegem",
      "3D printing bedrijf erwetegem",
      "3D printen nabij erwetegem",
      "3D model laten printen erwetegem",
    ],
    metaDescription: "Professionele 3D prints in Erwetegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-elene",
    city: "Elene",
    relatedPhrases: [
      "3D print service elene",
      "rapid prototyping elene",
      "3D printing bedrijf elene",
      "3D printen nabij elene",
      "3D model laten printen elene",
    ],
    metaDescription: "Professionele 3D prints in Elene voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-godveerdegem",
    city: "Godveerdegem",
    relatedPhrases: [
      "3D print service godveerdegem",
      "rapid prototyping godveerdegem",
      "3D printing bedrijf godveerdegem",
      "3D printen nabij godveerdegem",
      "3D model laten printen godveerdegem",
    ],
    metaDescription: "Professionele 3D prints in Godveerdegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-grotenberge",
    city: "Grotenberge",
    relatedPhrases: [
      "3D print service grotenberge",
      "rapid prototyping grotenberge",
      "3D printing bedrijf grotenberge",
      "3D printen nabij grotenberge",
      "3D model laten printen grotenberge",
    ],
    metaDescription: "Professionele 3D prints in Grotenberge voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-leeuwergem",
    city: "Leeuwergem",
    relatedPhrases: [
      "3D print service leeuwergem",
      "rapid prototyping leeuwergem",
      "3D printing bedrijf leeuwergem",
      "3D printen nabij leeuwergem",
      "3D model laten printen leeuwergem",
    ],
    metaDescription: "Professionele 3D prints in Leeuwergem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-oombergen",
    city: "Oombergen",
    relatedPhrases: [
      "3D print service oombergen",
      "rapid prototyping oombergen",
      "3D printing bedrijf oombergen",
      "3D printen nabij oombergen",
      "3D model laten printen oombergen",
    ],
    metaDescription: "Professionele 3D prints in Oombergen voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-goriks-oudenhove",
    city: "Sint-Goriks-Oudenhove",
    relatedPhrases: [
      "3D print service sint-goriks-oudenhove",
      "rapid prototyping sint-goriks-oudenhove",
      "3D printing bedrijf sint-goriks-oudenhove",
      "3D printen nabij sint-goriks-oudenhove",
      "3D model laten printen sint-goriks-oudenhove",
    ],
    metaDescription: "Professionele 3D prints in Sint-Goriks-Oudenhove voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-maria-oudenhove",
    city: "Sint-Maria-Oudenhove",
    relatedPhrases: [
      "3D print service sint-maria-oudenhove",
      "rapid prototyping sint-maria-oudenhove",
      "3D printing bedrijf sint-maria-oudenhove",
      "3D printen nabij sint-maria-oudenhove",
      "3D model laten printen sint-maria-oudenhove",
    ],
    metaDescription: "Professionele 3D prints in Sint-Maria-Oudenhove voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-strijpen",
    city: "Strijpen",
    relatedPhrases: [
      "3D print service strijpen",
      "rapid prototyping strijpen",
      "3D printing bedrijf strijpen",
      "3D printen nabij strijpen",
      "3D model laten printen strijpen",
    ],
    metaDescription: "Professionele 3D prints in Strijpen voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-velzeke-ruddershove",
    city: "Velzeke-Ruddershove",
    relatedPhrases: [
      "3D print service velzeke-ruddershove",
      "rapid prototyping velzeke-ruddershove",
      "3D printing bedrijf velzeke-ruddershove",
      "3D printen nabij velzeke-ruddershove",
      "3D model laten printen velzeke-ruddershove",
    ],
    metaDescription: "Professionele 3D prints in Velzeke-Ruddershove voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-baardegem",
    city: "Baardegem",
    relatedPhrases: [
      "3D print service baardegem",
      "rapid prototyping baardegem",
      "3D printing bedrijf baardegem",
      "3D printen nabij baardegem",
      "3D model laten printen baardegem",
    ],
    metaDescription: "Professionele 3D prints in Baardegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-erembodegem",
    city: "Erembodegem",
    relatedPhrases: [
      "3D print service erembodegem",
      "rapid prototyping erembodegem",
      "3D printing bedrijf erembodegem",
      "3D printen nabij erembodegem",
      "3D model laten printen erembodegem",
    ],
    metaDescription: "Professionele 3D prints in Erembodegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-gijzegem",
    city: "Gijzegem",
    relatedPhrases: [
      "3D print service gijzegem",
      "rapid prototyping gijzegem",
      "3D printing bedrijf gijzegem",
      "3D printen nabij gijzegem",
      "3D model laten printen gijzegem",
    ],
    metaDescription: "Professionele 3D prints in Gijzegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-herdersem",
    city: "Herdersem",
    relatedPhrases: [
      "3D print service herdersem",
      "rapid prototyping herdersem",
      "3D printing bedrijf herdersem",
      "3D printen nabij herdersem",
      "3D model laten printen herdersem",
    ],
    metaDescription: "Professionele 3D prints in Herdersem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-hofstade",
    city: "Hofstade",
    relatedPhrases: [
      "3D print service hofstade",
      "rapid prototyping hofstade",
      "3D printing bedrijf hofstade",
      "3D printen nabij hofstade",
      "3D model laten printen hofstade",
    ],
    metaDescription: "Professionele 3D prints in Hofstade voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-meldert",
    city: "Meldert",
    relatedPhrases: [
      "3D print service meldert",
      "rapid prototyping meldert",
      "3D printing bedrijf meldert",
      "3D printen nabij meldert",
      "3D model laten printen meldert",
    ],
    metaDescription: "Professionele 3D prints in Meldert voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-moorsel",
    city: "Moorsel",
    relatedPhrases: [
      "3D print service moorsel",
      "rapid prototyping moorsel",
      "3D printing bedrijf moorsel",
      "3D printen nabij moorsel",
      "3D model laten printen moorsel",
    ],
    metaDescription: "Professionele 3D prints in Moorsel voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-nieuwerkerken",
    city: "Nieuwerkerken",
    relatedPhrases: [
      "3D print service nieuwerkerken",
      "rapid prototyping nieuwerkerken",
      "3D printing bedrijf nieuwerkerken",
      "3D printen nabij nieuwerkerken",
      "3D model laten printen nieuwerkerken",
    ],
    metaDescription: "Professionele 3D prints in Nieuwerkerken voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-ninove",
    city: "Ninove",
    relatedPhrases: [
      "3D print service Ninove",
      "rapid prototyping Ninove",
      "3D printing bedrijf Ninove",
      "3D printen nabij Ninove",
      "3D model laten printen Ninove",
    ],
    metaDescription: "Professionele 3D prints in Ninove voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-appelterre-eichem",
    city: "Appelterre-Eichem",
    relatedPhrases: [
      "3D print service Appelterre-Eichem",
      "rapid prototyping Appelterre-Eichem",
      "3D printing bedrijf Appelterre-Eichem",
      "3D printen nabij Appelterre-Eichem",
      "3D model laten printen Appelterre-Eichem",
    ],
    metaDescription: "Professionele 3D prints in Appelterre-Eichem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-aspelare",
    city: "Aspelare",
    relatedPhrases: [
      "3D print service Aspelare",
      "rapid prototyping Aspelare",
      "3D printing bedrijf Aspelare",
      "3D printen nabij Aspelare",
      "3D model laten printen Aspelare",
    ],
    metaDescription: "Professionele 3D prints in Aspelare voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-denderwindeke",
    city: "Denderwindeke",
    relatedPhrases: [
      "3D print service Denderwindeke",
      "rapid prototyping Denderwindeke",
      "3D printing bedrijf Denderwindeke",
      "3D printen nabij Denderwindeke",
      "3D model laten printen Denderwindeke",
    ],
    metaDescription: "Professionele 3D prints in Denderwindeke voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-lieferinge",
    city: "Lieferinge",
    relatedPhrases: [
      "3D print service Lieferinge",
      "rapid prototyping Lieferinge",
      "3D printing bedrijf Lieferinge",
      "3D printen nabij Lieferinge",
      "3D model laten printen Lieferinge",
    ],
    metaDescription: "Professionele 3D prints in Lieferinge voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-meerbeke",
    city: "Meerbeke",
    relatedPhrases: [
      "3D print service Meerbeke",
      "rapid prototyping Meerbeke",
      "3D printing bedrijf Meerbeke",
      "3D printen nabij Meerbeke",
      "3D model laten printen Meerbeke",
    ],
    metaDescription: "Professionele 3D prints in Meerbeke voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-nederhasselt",
    city: "Nederhasselt",
    relatedPhrases: [
      "3D print service Nederhasselt",
      "rapid prototyping Nederhasselt",
      "3D printing bedrijf Nederhasselt",
      "3D printen nabij Nederhasselt",
      "3D model laten printen Nederhasselt",
    ],
    metaDescription: "Professionele 3D prints in Nederhasselt voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-neigem",
    city: "Neigem",
    relatedPhrases: [
      "3D print service Neigem",
      "rapid prototyping Neigem",
      "3D printing bedrijf Neigem",
      "3D printen nabij Neigem",
      "3D model laten printen Neigem",
    ],
    metaDescription: "Professionele 3D prints in Neigem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-okegem",
    city: "Okegem",
    relatedPhrases: [
      "3D print service Okegem",
      "rapid prototyping Okegem",
      "3D printing bedrijf Okegem",
      "3D printen nabij Okegem",
      "3D model laten printen Okegem",
    ],
    metaDescription: "Professionele 3D prints in Okegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-outer",
    city: "Outer",
    relatedPhrases: [
      "3D print service Outer",
      "rapid prototyping Outer",
      "3D printing bedrijf Outer",
      "3D printen nabij Outer",
      "3D model laten printen Outer",
    ],
    metaDescription: "Professionele 3D prints in Outer voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-pollare",
    city: "Pollare",
    relatedPhrases: [
      "3D print service Pollare",
      "rapid prototyping Pollare",
      "3D printing bedrijf Pollare",
      "3D printen nabij Pollare",
      "3D model laten printen Pollare",
    ],
    metaDescription: "Professionele 3D prints in Pollare voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-voorde",
    city: "Voorde",
    relatedPhrases: [
      "3D print service Voorde",
      "rapid prototyping Voorde",
      "3D printing bedrijf Voorde",
      "3D printen nabij Voorde",
      "3D model laten printen Voorde",
    ],
    metaDescription: "Professionele 3D prints in Voorde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-appels",
    city: "Appels",
    relatedPhrases: [
      "3D print service appels",
      "rapid prototyping appels",
      "3D printing bedrijf appels",
      "3D printen nabij appels",
      "3D model laten printen appels",
    ],
    metaDescription: "Professionele 3D prints in Appels voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-baasrode",
    city: "Baasrode",
    relatedPhrases: [
      "3D print service baasrode",
      "rapid prototyping baasrode",
      "3D printing bedrijf baasrode",
      "3D printen nabij baasrode",
      "3D model laten printen baasrode",
    ],
    metaDescription: "Professionele 3D prints in Baasrode voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-grembergen",
    city: "Grembergen",
    relatedPhrases: [
      "3D print service grembergen",
      "rapid prototyping grembergen",
      "3D printing bedrijf grembergen",
      "3D printen nabij grembergen",
      "3D model laten printen grembergen",
    ],
    metaDescription: "Professionele 3D prints in Grembergen voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-mespelare",
    city: "Mespelare",
    relatedPhrases: [
      "3D print service mespelare",
      "rapid prototyping mespelare",
      "3D printing bedrijf mespelare",
      "3D printen nabij mespelare",
      "3D model laten printen mespelare",
    ],
    metaDescription: "Professionele 3D prints in Mespelare voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-oudegem",
    city: "Oudegem",
    relatedPhrases: [
      "3D print service oudegem",
      "rapid prototyping oudegem",
      "3D printing bedrijf oudegem",
      "3D printen nabij oudegem",
      "3D model laten printen oudegem",
    ],
    metaDescription: "Professionele 3D prints in Oudegem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-schoonaarde",
    city: "Schoonaarde",
    relatedPhrases: [
      "3D print service schoonaarde",
      "rapid prototyping schoonaarde",
      "3D printing bedrijf schoonaarde",
      "3D printen nabij schoonaarde",
      "3D model laten printen schoonaarde",
    ],
    metaDescription: "Professionele 3D prints in Schoonaarde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-gillis-dendermonde",
    city: "Sint-Gillis-Dendermonde",
    relatedPhrases: [
      "3D print service sint-gillis-dendermonde",
      "rapid prototyping sint-gillis-dendermonde",
      "3D printing bedrijf sint-gillis-dendermonde",
      "3D printen nabij sint-gillis-dendermonde",
      "3D model laten printen sint-gillis-dendermonde",
    ],
    metaDescription: "Professionele 3D prints in Sint-Gillis-Dendermonde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-desteldonk",
    city: "Desteldonk",
    relatedPhrases: [
      "3D print service desteldonk",
      "rapid prototyping desteldonk",
      "3D printing bedrijf desteldonk",
      "3D printen nabij desteldonk",
      "3D model laten printen desteldonk",
    ],
    metaDescription: "Professionele 3D prints in Desteldonk voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-drongen",
    city: "Drongen",
    relatedPhrases: [
      "3D print service drongen",
      "rapid prototyping drongen",
      "3D printing bedrijf drongen",
      "3D printen nabij drongen",
      "3D model laten printen drongen",
    ],
    metaDescription: "Professionele 3D prints in Drongen voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-ledeberg",
    city: "Ledeberg",
    relatedPhrases: [
      "3D print service ledeberg",
      "rapid prototyping ledeberg",
      "3D printing bedrijf ledeberg",
      "3D printen nabij ledeberg",
      "3D model laten printen ledeberg",
    ],
    metaDescription: "Professionele 3D prints in Ledeberg voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-mariakerke",
    city: "Mariakerke",
    relatedPhrases: [
      "3D print service mariakerke",
      "rapid prototyping mariakerke",
      "3D printing bedrijf mariakerke",
      "3D printen nabij mariakerke",
      "3D model laten printen mariakerke",
    ],
    metaDescription: "Professionele 3D prints in Mariakerke voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-mendonk",
    city: "Mendonk",
    relatedPhrases: [
      "3D print service mendonk",
      "rapid prototyping mendonk",
      "3D printing bedrijf mendonk",
      "3D printen nabij mendonk",
      "3D model laten printen mendonk",
    ],
    metaDescription: "Professionele 3D prints in Mendonk voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-oostakker",
    city: "Oostakker",
    relatedPhrases: [
      "3D print service oostakker",
      "rapid prototyping oostakker",
      "3D printing bedrijf oostakker",
      "3D printen nabij oostakker",
      "3D model laten printen oostakker",
    ],
    metaDescription: "Professionele 3D prints in Oostakker voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-amandsberg",
    city: "Sint-Amandsberg",
    relatedPhrases: [
      "3D print service sint-amandsberg",
      "rapid prototyping sint-amandsberg",
      "3D printing bedrijf sint-amandsberg",
      "3D printen nabij sint-amandsberg",
      "3D model laten printen sint-amandsberg",
    ],
    metaDescription: "Professionele 3D prints in Sint-Amandsberg voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-kruis-winkel",
    city: "Sint-Kruis-Winkel",
    relatedPhrases: [
      "3D print service sint-kruis-winkel",
      "rapid prototyping sint-kruis-winkel",
      "3D printing bedrijf sint-kruis-winkel",
      "3D printen nabij sint-kruis-winkel",
      "3D model laten printen sint-kruis-winkel",
    ],
    metaDescription: "Professionele 3D prints in Sint-Kruis-Winkel voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-sint-denijs-westrem",
    city: "Sint-Denijs-Westrem",
    relatedPhrases: [
      "3D print service sint-denijs-westrem",
      "rapid prototyping sint-denijs-westrem",
      "3D printing bedrijf sint-denijs-westrem",
      "3D printen nabij sint-denijs-westrem",
      "3D model laten printen sint-denijs-westrem",
    ],
    metaDescription: "Professionele 3D prints in Sint-Denijs-Westrem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-wondelgem",
    city: "Wondelgem",
    relatedPhrases: [
      "3D print service wondelgem",
      "rapid prototyping wondelgem",
      "3D printing bedrijf wondelgem",
      "3D printen nabij wondelgem",
      "3D model laten printen wondelgem",
    ],
    metaDescription: "Professionele 3D prints in Wondelgem voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
  {
    slug: "3d-printen-in-zwijnaarde",
    city: "Zwijnaarde",
    relatedPhrases: [
      "3D print service zwijnaarde",
      "rapid prototyping zwijnaarde",
      "3D printing bedrijf zwijnaarde",
      "3D printen nabij zwijnaarde",
      "3D model laten printen zwijnaarde",
    ],
    metaDescription: "Professionele 3D prints in Zwijnaarde voor prototypes, mallen en functionele onderdelen. Upload je model en ontvang snel een offerte bij X3DPrints.",
  },
];
// --- HELPERS -------------------------------------------------
function normSlug(s: string): string {
  return s.trim().toLowerCase().replace(/^\/|\/$/g, "")
}

export function buildDefaultRelatedPhrases(city: string): string[] {
  const c = city.trim()
  return [
    `3D printen in ${c}`,
    `3D print service ${c}`,
    `prototypes 3D print ${c}`,
    `FDM 3D print ${c}`,
    `PLA PETG TPU ${c}`,
  ]
}

export function getAllLocationSlugs(): string[] {
  return locations.map((l) => l.slug)
}

export function getLocationBySlug(slug: string): Location | undefined {
  const s = normSlug(slug)
  return locations.find((l) => normSlug(l.slug) === s)
}

export function listLocations(): Location[] {
  return [...locations]
}