// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
}


// Validate ..\..\app\(home)\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(home)\\page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ..\..\app\(pages)\3d-modellen-vinden\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\3d-modellen-vinden\\page.js")
  handler satisfies AppPageConfig<"/3d-modellen-vinden">
}

// Validate ..\..\app\(pages)\3d-modelleren\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\3d-modelleren\\page.js")
  handler satisfies AppPageConfig<"/3d-modelleren">
}

// Validate ..\..\app\(pages)\3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\3d-printen\\page.js")
  handler satisfies AppPageConfig<"/3d-printen">
}

// Validate ..\..\app\(pages)\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/[slug]">
}

// Validate ..\..\app\(pages)\about\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\about\\page.js")
  handler satisfies AppPageConfig<"/about">
}

// Validate ..\..\app\(pages)\algemene-voorwaarden\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\algemene-voorwaarden\\page.js")
  handler satisfies AppPageConfig<"/algemene-voorwaarden">
}

// Validate ..\..\app\(pages)\blog\3d-geprinte-platen-nasiam\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-geprinte-platen-nasiam\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-geprinte-platen-nasiam">
}

// Validate ..\..\app\(pages)\blog\3d-print-assemblage-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-assemblage-gids\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-assemblage-gids">
}

// Validate ..\..\app\(pages)\blog\3d-print-kosten-besparen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-kosten-besparen\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-kosten-besparen">
}

// Validate ..\..\app\(pages)\blog\3d-print-materiaal-voor-zichtwerk\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-materiaal-voor-zichtwerk\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-materiaal-voor-zichtwerk">
}

// Validate ..\..\app\(pages)\blog\3d-print-materialen-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-materialen-gids\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-materialen-gids">
}

// Validate ..\..\app\(pages)\blog\3d-print-offerte-aanvragen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-offerte-aanvragen\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-offerte-aanvragen">
}

// Validate ..\..\app\(pages)\blog\3d-print-ontwerp-checklist\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-ontwerp-checklist\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-ontwerp-checklist">
}

// Validate ..\..\app\(pages)\blog\3d-print-ontwerp-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-ontwerp-gids\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-ontwerp-gids">
}

// Validate ..\..\app\(pages)\blog\3d-print-prijs-per-stuk\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-prijs-per-stuk\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-prijs-per-stuk">
}

// Validate ..\..\app\(pages)\blog\3d-print-prijzen-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-print-prijzen-gids\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-print-prijzen-gids">
}

// Validate ..\..\app\(pages)\blog\3d-printen-back-to-school\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-back-to-school\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-back-to-school">
}

// Validate ..\..\app\(pages)\blog\3d-printen-herfst-halloween\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-herfst-halloween\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-herfst-halloween">
}

// Validate ..\..\app\(pages)\blog\3d-printen-in-de-buurt\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-in-de-buurt\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-in-de-buurt">
}

// Validate ..\..\app\(pages)\blog\3d-printen-lente-pasen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-lente-pasen\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-lente-pasen">
}

// Validate ..\..\app\(pages)\blog\3d-printen-mini-figuren\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-mini-figuren\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-mini-figuren">
}

// Validate ..\..\app\(pages)\blog\3d-printen-op-bestelling\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-op-bestelling\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-op-bestelling">
}

// Validate ..\..\app\(pages)\blog\3d-printen-vaderdag-moederdag\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-vaderdag-moederdag\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-vaderdag-moederdag">
}

// Validate ..\..\app\(pages)\blog\3d-printen-valentijn\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-valentijn\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-valentijn">
}

// Validate ..\..\app\(pages)\blog\3d-printen-voor-beginners\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-voor-beginners\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-voor-beginners">
}

// Validate ..\..\app\(pages)\blog\3d-printen-winter-kerst-nieuwjaar\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-winter-kerst-nieuwjaar\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-winter-kerst-nieuwjaar">
}

// Validate ..\..\app\(pages)\blog\3d-printen-zomer\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printen-zomer\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printen-zomer">
}

// Validate ..\..\app\(pages)\blog\3d-printing-marketing-events\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\3d-printing-marketing-events\\page.js")
  handler satisfies AppPageConfig<"/blog/3d-printing-marketing-events">
}

// Validate ..\..\app\(pages)\blog\bestanden-voor-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\bestanden-voor-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/bestanden-voor-3d-printen">
}

// Validate ..\..\app\(pages)\blog\beste-instellingen-bambu-printer\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\beste-instellingen-bambu-printer\\page.js")
  handler satisfies AppPageConfig<"/blog/beste-instellingen-bambu-printer">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pc-fr\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pc-fr\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pc-fr">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pc\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pc\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pc">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-petg\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-petg\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-petg">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pla-glow\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pla-glow\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pla-glow">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pla-marble\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pla-marble\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pla-marble">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pla-metal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pla-metal\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pla-metal">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pla-silk-plus\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pla-silk-plus\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pla-silk-plus">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pla-wood\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pla-wood\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pla-wood">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-pla\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-pla\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-pla">
}

// Validate ..\..\app\(pages)\blog\filament-vrijdag-tpu\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\filament-vrijdag-tpu\\page.js")
  handler satisfies AppPageConfig<"/blog/filament-vrijdag-tpu">
}

// Validate ..\..\app\(pages)\blog\finishing-friday-schuren-primen-lakken\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\finishing-friday-schuren-primen-lakken\\page.js")
  handler satisfies AppPageConfig<"/blog/finishing-friday-schuren-primen-lakken">
}

// Validate ..\..\app\(pages)\blog\gridfinity-modulair-opslagsysteem\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\gridfinity-modulair-opslagsysteem\\page.js")
  handler satisfies AppPageConfig<"/blog/gridfinity-modulair-opslagsysteem">
}

// Validate ..\..\app\(pages)\blog\hittebestendig-3d-print-materiaal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\hittebestendig-3d-print-materiaal\\page.js")
  handler satisfies AppPageConfig<"/blog/hittebestendig-3d-print-materiaal">
}

// Validate ..\..\app\(pages)\blog\hoe-3d-print-je-onderdelen-voor-buitengebruik\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\hoe-3d-print-je-onderdelen-voor-buitengebruik\\page.js")
  handler satisfies AppPageConfig<"/blog/hoe-3d-print-je-onderdelen-voor-buitengebruik">
}

// Validate ..\..\app\(pages)\blog\hoe-lang-duurt-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\hoe-lang-duurt-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/hoe-lang-duurt-3d-printen">
}

// Validate ..\..\app\(pages)\blog\hoeveel-kost-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\hoeveel-kost-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/hoeveel-kost-3d-printen">
}

// Validate ..\..\app\(pages)\blog\ikea-onderdelen-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\ikea-onderdelen-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/ikea-onderdelen-3d-printen">
}

// Validate ..\..\app\(pages)\blog\juiste-3d-print-materiaal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\juiste-3d-print-materiaal\\page.js")
  handler satisfies AppPageConfig<"/blog/juiste-3d-print-materiaal">
}

// Validate ..\..\app\(pages)\blog\kabelmanagement-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\kabelmanagement-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/kabelmanagement-3d-printen">
}

// Validate ..\..\app\(pages)\blog\kapot-onderdeel-laten-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\kapot-onderdeel-laten-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/kapot-onderdeel-laten-printen">
}

// Validate ..\..\app\(pages)\blog\maker-monday-fdm-scharnieren\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-fdm-scharnieren\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-fdm-scharnieren">
}

// Validate ..\..\app\(pages)\blog\maker-monday-schroefdraad-bevestigingen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-schroefdraad-bevestigingen\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-schroefdraad-bevestigingen">
}

// Validate ..\..\app\(pages)\blog\maker-monday-schroefdraad-inserts\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-schroefdraad-inserts\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-schroefdraad-inserts">
}

// Validate ..\..\app\(pages)\blog\maker-monday-snapfit-parts\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-snapfit-parts\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-snapfit-parts">
}

// Validate ..\..\app\(pages)\blog\maker-monday-snapfits\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-snapfits\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-snapfits">
}

// Validate ..\..\app\(pages)\blog\maker-monday-toleranties-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-toleranties-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-toleranties-3d-printen">
}

// Validate ..\..\app\(pages)\blog\maker-monday-wanddiktes-ribs\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-wanddiktes-ribs\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-wanddiktes-ribs">
}

// Validate ..\..\app\(pages)\blog\maker-monday-warping-layer-cracks\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\maker-monday-warping-layer-cracks\\page.js")
  handler satisfies AppPageConfig<"/blog/maker-monday-warping-layer-cracks">
}

// Validate ..\..\app\(pages)\blog\octopus-accountancy-3d-print-goodies\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\octopus-accountancy-3d-print-goodies\\page.js")
  handler satisfies AppPageConfig<"/blog/octopus-accountancy-3d-print-goodies">
}

// Validate ..\..\app\(pages)\blog\ontwerp-3d-printbaar-model\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\ontwerp-3d-printbaar-model\\page.js")
  handler satisfies AppPageConfig<"/blog/ontwerp-3d-printbaar-model">
}

// Validate ..\..\app\(pages)\blog\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\page.js")
  handler satisfies AppPageConfig<"/blog">
}

// Validate ..\..\app\(pages)\blog\pla-vs-petg\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\pla-vs-petg\\page.js")
  handler satisfies AppPageConfig<"/blog/pla-vs-petg">
}

// Validate ..\..\app\(pages)\blog\prototyping-kleine-reeksen-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\prototyping-kleine-reeksen-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/prototyping-kleine-reeksen-3d-printen">
}

// Validate ..\..\app\(pages)\blog\relatiegeschenken-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\relatiegeschenken-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/relatiegeschenken-3d-printen">
}

// Validate ..\..\app\(pages)\blog\retail-pos-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\retail-pos-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/retail-pos-3d-printen">
}

// Validate ..\..\app\(pages)\blog\sterke-3d-print-materialen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\sterke-3d-print-materialen\\page.js")
  handler satisfies AppPageConfig<"/blog/sterke-3d-print-materialen">
}

// Validate ..\..\app\(pages)\blog\tool-organizers-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\tool-organizers-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/tool-organizers-3d-printen">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-auto-fiets\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-auto-fiets\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-auto-fiets">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-events\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-events\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-events">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-headset-spacer-racefiets\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-headset-spacer-racefiets\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-headset-spacer-racefiets">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-interieur\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-interieur\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-interieur">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-productontwikkeling\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-productontwikkeling\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-productontwikkeling">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-retail-displays\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-retail-displays\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-retail-displays">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-scholen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-scholen\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-scholen">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-stem\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-stem\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-stem">
}

// Validate ..\..\app\(pages)\blog\use-case-dinsdag-tabletop\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-case-dinsdag-tabletop\\page.js")
  handler satisfies AppPageConfig<"/blog/use-case-dinsdag-tabletop">
}

// Validate ..\..\app\(pages)\blog\use-cases-tpu\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\use-cases-tpu\\page.js")
  handler satisfies AppPageConfig<"/blog/use-cases-tpu">
}

// Validate ..\..\app\(pages)\blog\vervangstuk-huishoudtoestel-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\vervangstuk-huishoudtoestel-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/blog/vervangstuk-huishoudtoestel-3d-printen">
}

// Validate ..\..\app\(pages)\cases\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\cases\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/cases/[slug]">
}

// Validate ..\..\app\(pages)\cases\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\cases\\page.js")
  handler satisfies AppPageConfig<"/cases">
}

// Validate ..\..\app\(pages)\cases\selectieve-val-aziatische-hoornaar-sint-lievens-houtem\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\cases\\selectieve-val-aziatische-hoornaar-sint-lievens-houtem\\page.js")
  handler satisfies AppPageConfig<"/cases/selectieve-val-aziatische-hoornaar-sint-lievens-houtem">
}

// Validate ..\..\app\(pages)\contact\bedankt\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\contact\\bedankt\\page.js")
  handler satisfies AppPageConfig<"/contact/bedankt">
}

// Validate ..\..\app\(pages)\contact\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\contact\\page.js")
  handler satisfies AppPageConfig<"/contact">
}

// Validate ..\..\app\(pages)\cookies\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\cookies\\page.js")
  handler satisfies AppPageConfig<"/cookies">
}

// Validate ..\..\app\(pages)\crm\orders\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\crm\\orders\\page.js")
  handler satisfies AppPageConfig<"/crm/orders">
}

// Validate ..\..\app\(pages)\crm\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\crm\\page.js")
  handler satisfies AppPageConfig<"/crm">
}

// Validate ..\..\app\(pages)\faq\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\faq\\page.js")
  handler satisfies AppPageConfig<"/faq">
}

// Validate ..\..\app\(pages)\locaties\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\locaties\\page.js")
  handler satisfies AppPageConfig<"/locaties">
}

// Validate ..\..\app\(pages)\lokaal-belgisch\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\lokaal-belgisch\\page.js")
  handler satisfies AppPageConfig<"/lokaal-belgisch">
}

// Validate ..\..\app\(pages)\machine-readable-resources\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\machine-readable-resources\\page.js")
  handler satisfies AppPageConfig<"/machine-readable-resources">
}

// Validate ..\..\app\(pages)\materials\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\materials\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/materials/[slug]">
}

// Validate ..\..\app\(pages)\materials\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\materials\\page.js")
  handler satisfies AppPageConfig<"/materials">
}

// Validate ..\..\app\(pages)\organizers\custom\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\organizers\\custom\\page.js")
  handler satisfies AppPageConfig<"/organizers/custom">
}

// Validate ..\..\app\(pages)\organizers\modugrid\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\organizers\\modugrid\\page.js")
  handler satisfies AppPageConfig<"/organizers/modugrid">
}

// Validate ..\..\app\(pages)\organizers\packout\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\organizers\\packout\\page.js")
  handler satisfies AppPageConfig<"/organizers/packout">
}

// Validate ..\..\app\(pages)\organizers\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\organizers\\page.js")
  handler satisfies AppPageConfig<"/organizers">
}

// Validate ..\..\app\(pages)\organizers\tstak\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\organizers\\tstak\\page.js")
  handler satisfies AppPageConfig<"/organizers/tstak">
}

// Validate ..\..\app\(pages)\portfolio\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\portfolio\\page.js")
  handler satisfies AppPageConfig<"/portfolio">
}

// Validate ..\..\app\(pages)\pricing\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\pricing\\page.js")
  handler satisfies AppPageConfig<"/pricing">
}

// Validate ..\..\app\(pages)\prijzen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\prijzen\\page.js")
  handler satisfies AppPageConfig<"/prijzen">
}

// Validate ..\..\app\(pages)\privacy\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\privacy\\page.js")
  handler satisfies AppPageConfig<"/privacy">
}

// Validate ..\..\app\(pages)\retour-herroepingsrecht\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\retour-herroepingsrecht\\page.js")
  handler satisfies AppPageConfig<"/retour-herroepingsrecht">
}

// Validate ..\..\app\(pages)\segments\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\segments\\page.js")
  handler satisfies AppPageConfig<"/segments">
}

// Validate ..\..\app\(pages)\services\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\services\\page.js")
  handler satisfies AppPageConfig<"/services">
}

// Validate ..\..\app\(pages)\shop\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\shop\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/shop/[slug]">
}

// Validate ..\..\app\(pages)\shop\cart\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\shop\\cart\\page.js")
  handler satisfies AppPageConfig<"/shop/cart">
}

// Validate ..\..\app\(pages)\shop\checkout\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\shop\\checkout\\page.js")
  handler satisfies AppPageConfig<"/shop/checkout">
}

// Validate ..\..\app\(pages)\shop\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\shop\\page.js")
  handler satisfies AppPageConfig<"/shop">
}

// Validate ..\..\app\(pages)\sustainability\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\sustainability\\page.js")
  handler satisfies AppPageConfig<"/sustainability">
}

// Validate ..\..\app\(pages)\valentijn-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\valentijn-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/valentijn-3d-printen">
}

// Validate ..\..\app\(pages)\viewer\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\viewer\\page.js")
  handler satisfies AppPageConfig<"/viewer">
}

// Validate ..\..\app\en\(home)\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(home)\\page.js")
  handler satisfies AppPageConfig<"/en">
}

// Validate ..\..\app\en\(pages)\3d-modellen-vinden\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\3d-modellen-vinden\\page.js")
  handler satisfies AppPageConfig<"/en/3d-modellen-vinden">
}

// Validate ..\..\app\en\(pages)\3d-modelleren\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\3d-modelleren\\page.js")
  handler satisfies AppPageConfig<"/en/3d-modelleren">
}

// Validate ..\..\app\en\(pages)\3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/3d-printen">
}

// Validate ..\..\app\en\(pages)\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/en/[slug]">
}

// Validate ..\..\app\en\(pages)\about\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\about\\page.js")
  handler satisfies AppPageConfig<"/en/about">
}

// Validate ..\..\app\en\(pages)\algemene-voorwaarden\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\algemene-voorwaarden\\page.js")
  handler satisfies AppPageConfig<"/en/algemene-voorwaarden">
}

// Validate ..\..\app\en\(pages)\blog\3d-geprinte-platen-nasiam\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-geprinte-platen-nasiam\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-geprinte-platen-nasiam">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-assemblage-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-assemblage-gids\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-assemblage-gids">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-kosten-besparen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-kosten-besparen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-kosten-besparen">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-materiaal-voor-zichtwerk\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-materiaal-voor-zichtwerk\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-materiaal-voor-zichtwerk">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-materialen-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-materialen-gids\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-materialen-gids">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-offerte-aanvragen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-offerte-aanvragen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-offerte-aanvragen">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-ontwerp-checklist\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-ontwerp-checklist\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-ontwerp-checklist">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-ontwerp-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-ontwerp-gids\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-ontwerp-gids">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-prijs-per-stuk\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-prijs-per-stuk\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-prijs-per-stuk">
}

// Validate ..\..\app\en\(pages)\blog\3d-print-prijzen-gids\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-print-prijzen-gids\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-print-prijzen-gids">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-back-to-school\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-back-to-school\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-back-to-school">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-herfst-halloween\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-herfst-halloween\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-herfst-halloween">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-in-de-buurt\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-in-de-buurt\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-in-de-buurt">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-lente-pasen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-lente-pasen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-lente-pasen">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-mini-figuren\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-mini-figuren\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-mini-figuren">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-op-bestelling\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-op-bestelling\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-op-bestelling">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-vaderdag-moederdag\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-vaderdag-moederdag\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-vaderdag-moederdag">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-valentijn\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-valentijn\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-valentijn">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-voor-beginners\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-voor-beginners\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-voor-beginners">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-winter-kerst-nieuwjaar\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-winter-kerst-nieuwjaar\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-winter-kerst-nieuwjaar">
}

// Validate ..\..\app\en\(pages)\blog\3d-printen-zomer\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printen-zomer\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printen-zomer">
}

// Validate ..\..\app\en\(pages)\blog\3d-printing-marketing-events\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\3d-printing-marketing-events\\page.js")
  handler satisfies AppPageConfig<"/en/blog/3d-printing-marketing-events">
}

// Validate ..\..\app\en\(pages)\blog\bestanden-voor-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\bestanden-voor-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/bestanden-voor-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\beste-instellingen-bambu-printer\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\beste-instellingen-bambu-printer\\page.js")
  handler satisfies AppPageConfig<"/en/blog/beste-instellingen-bambu-printer">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pc-fr\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pc-fr\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pc-fr">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pc\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pc\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pc">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-petg\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-petg\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-petg">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pla-glow\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pla-glow\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pla-glow">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pla-marble\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pla-marble\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pla-marble">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pla-metal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pla-metal\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pla-metal">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pla-silk-plus\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pla-silk-plus\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pla-silk-plus">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pla-wood\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pla-wood\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pla-wood">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-pla\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-pla\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-pla">
}

// Validate ..\..\app\en\(pages)\blog\filament-vrijdag-tpu\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\filament-vrijdag-tpu\\page.js")
  handler satisfies AppPageConfig<"/en/blog/filament-vrijdag-tpu">
}

// Validate ..\..\app\en\(pages)\blog\finishing-friday-schuren-primen-lakken\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\finishing-friday-schuren-primen-lakken\\page.js")
  handler satisfies AppPageConfig<"/en/blog/finishing-friday-schuren-primen-lakken">
}

// Validate ..\..\app\en\(pages)\blog\gridfinity-modular-storage-system\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\gridfinity-modular-storage-system\\page.js")
  handler satisfies AppPageConfig<"/en/blog/gridfinity-modular-storage-system">
}

// Validate ..\..\app\en\(pages)\blog\hittebestendig-3d-print-materiaal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\hittebestendig-3d-print-materiaal\\page.js")
  handler satisfies AppPageConfig<"/en/blog/hittebestendig-3d-print-materiaal">
}

// Validate ..\..\app\en\(pages)\blog\hoe-3d-print-je-onderdelen-voor-buitengebruik\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\hoe-3d-print-je-onderdelen-voor-buitengebruik\\page.js")
  handler satisfies AppPageConfig<"/en/blog/hoe-3d-print-je-onderdelen-voor-buitengebruik">
}

// Validate ..\..\app\en\(pages)\blog\hoe-lang-duurt-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\hoe-lang-duurt-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/hoe-lang-duurt-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\hoeveel-kost-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\hoeveel-kost-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/hoeveel-kost-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\ikea-onderdelen-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\ikea-onderdelen-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/ikea-onderdelen-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\juiste-3d-print-materiaal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\juiste-3d-print-materiaal\\page.js")
  handler satisfies AppPageConfig<"/en/blog/juiste-3d-print-materiaal">
}

// Validate ..\..\app\en\(pages)\blog\kabelmanagement-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\kabelmanagement-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/kabelmanagement-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\kapot-onderdeel-laten-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\kapot-onderdeel-laten-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/kapot-onderdeel-laten-printen">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-fdm-scharnieren\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-fdm-scharnieren\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-fdm-scharnieren">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-schroefdraad-bevestigingen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-schroefdraad-bevestigingen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-schroefdraad-bevestigingen">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-schroefdraad-inserts\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-schroefdraad-inserts\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-schroefdraad-inserts">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-snapfit-parts\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-snapfit-parts\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-snapfit-parts">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-snapfits\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-snapfits\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-snapfits">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-toleranties-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-toleranties-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-toleranties-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-wanddiktes-ribs\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-wanddiktes-ribs\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-wanddiktes-ribs">
}

// Validate ..\..\app\en\(pages)\blog\maker-monday-warping-layer-cracks\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\maker-monday-warping-layer-cracks\\page.js")
  handler satisfies AppPageConfig<"/en/blog/maker-monday-warping-layer-cracks">
}

// Validate ..\..\app\en\(pages)\blog\octopus-accountancy-3d-print-goodies\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\octopus-accountancy-3d-print-goodies\\page.js")
  handler satisfies AppPageConfig<"/en/blog/octopus-accountancy-3d-print-goodies">
}

// Validate ..\..\app\en\(pages)\blog\ontwerp-3d-printbaar-model\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\ontwerp-3d-printbaar-model\\page.js")
  handler satisfies AppPageConfig<"/en/blog/ontwerp-3d-printbaar-model">
}

// Validate ..\..\app\en\(pages)\blog\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\page.js")
  handler satisfies AppPageConfig<"/en/blog">
}

// Validate ..\..\app\en\(pages)\blog\pla-vs-petg\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\pla-vs-petg\\page.js")
  handler satisfies AppPageConfig<"/en/blog/pla-vs-petg">
}

// Validate ..\..\app\en\(pages)\blog\prototyping-kleine-reeksen-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\prototyping-kleine-reeksen-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/prototyping-kleine-reeksen-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\relatiegeschenken-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\relatiegeschenken-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/relatiegeschenken-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\retail-pos-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\retail-pos-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/retail-pos-3d-printen">
}

// Validate ..\..\app\en\(pages)\blog\sterke-3d-print-materialen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\sterke-3d-print-materialen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/sterke-3d-print-materialen">
}

// Validate ..\..\app\en\(pages)\blog\tool-organizers-3d-printing\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\tool-organizers-3d-printing\\page.js")
  handler satisfies AppPageConfig<"/en/blog/tool-organizers-3d-printing">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-auto-fiets\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-auto-fiets\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-auto-fiets">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-events\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-events\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-events">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-headset-spacer-racefiets\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-headset-spacer-racefiets\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-headset-spacer-racefiets">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-interieur\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-interieur\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-interieur">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-productontwikkeling\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-productontwikkeling\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-productontwikkeling">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-retail-displays\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-retail-displays\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-retail-displays">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-scholen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-scholen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-scholen">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-stem\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-stem\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-stem">
}

// Validate ..\..\app\en\(pages)\blog\use-case-dinsdag-tabletop\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-case-dinsdag-tabletop\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-case-dinsdag-tabletop">
}

// Validate ..\..\app\en\(pages)\blog\use-cases-tpu\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\use-cases-tpu\\page.js")
  handler satisfies AppPageConfig<"/en/blog/use-cases-tpu">
}

// Validate ..\..\app\en\(pages)\blog\vervangstuk-huishoudtoestel-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\vervangstuk-huishoudtoestel-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/blog/vervangstuk-huishoudtoestel-3d-printen">
}

// Validate ..\..\app\en\(pages)\cases\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\cases\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/en/cases/[slug]">
}

// Validate ..\..\app\en\(pages)\cases\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\cases\\page.js")
  handler satisfies AppPageConfig<"/en/cases">
}

// Validate ..\..\app\en\(pages)\cases\selectieve-val-aziatische-hoornaar-sint-lievens-houtem\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\cases\\selectieve-val-aziatische-hoornaar-sint-lievens-houtem\\page.js")
  handler satisfies AppPageConfig<"/en/cases/selectieve-val-aziatische-hoornaar-sint-lievens-houtem">
}

// Validate ..\..\app\en\(pages)\contact\bedankt\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\contact\\bedankt\\page.js")
  handler satisfies AppPageConfig<"/en/contact/bedankt">
}

// Validate ..\..\app\en\(pages)\contact\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\contact\\page.js")
  handler satisfies AppPageConfig<"/en/contact">
}

// Validate ..\..\app\en\(pages)\cookies\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\cookies\\page.js")
  handler satisfies AppPageConfig<"/en/cookies">
}

// Validate ..\..\app\en\(pages)\faq\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\faq\\page.js")
  handler satisfies AppPageConfig<"/en/faq">
}

// Validate ..\..\app\en\(pages)\locaties\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\locaties\\page.js")
  handler satisfies AppPageConfig<"/en/locaties">
}

// Validate ..\..\app\en\(pages)\lokaal-belgisch\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\lokaal-belgisch\\page.js")
  handler satisfies AppPageConfig<"/en/lokaal-belgisch">
}

// Validate ..\..\app\en\(pages)\machine-readable-resources\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\machine-readable-resources\\page.js")
  handler satisfies AppPageConfig<"/en/machine-readable-resources">
}

// Validate ..\..\app\en\(pages)\materials\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\materials\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/en/materials/[slug]">
}

// Validate ..\..\app\en\(pages)\materials\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\materials\\page.js")
  handler satisfies AppPageConfig<"/en/materials">
}

// Validate ..\..\app\en\(pages)\organizers\custom\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\organizers\\custom\\page.js")
  handler satisfies AppPageConfig<"/en/organizers/custom">
}

// Validate ..\..\app\en\(pages)\organizers\modugrid\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\organizers\\modugrid\\page.js")
  handler satisfies AppPageConfig<"/en/organizers/modugrid">
}

// Validate ..\..\app\en\(pages)\organizers\packout\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\organizers\\packout\\page.js")
  handler satisfies AppPageConfig<"/en/organizers/packout">
}

// Validate ..\..\app\en\(pages)\organizers\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\organizers\\page.js")
  handler satisfies AppPageConfig<"/en/organizers">
}

// Validate ..\..\app\en\(pages)\organizers\tstak\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\organizers\\tstak\\page.js")
  handler satisfies AppPageConfig<"/en/organizers/tstak">
}

// Validate ..\..\app\en\(pages)\portfolio\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\portfolio\\page.js")
  handler satisfies AppPageConfig<"/en/portfolio">
}

// Validate ..\..\app\en\(pages)\pricing\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\pricing\\page.js")
  handler satisfies AppPageConfig<"/en/pricing">
}

// Validate ..\..\app\en\(pages)\prijzen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\prijzen\\page.js")
  handler satisfies AppPageConfig<"/en/prijzen">
}

// Validate ..\..\app\en\(pages)\privacy\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\privacy\\page.js")
  handler satisfies AppPageConfig<"/en/privacy">
}

// Validate ..\..\app\en\(pages)\retour-herroepingsrecht\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\retour-herroepingsrecht\\page.js")
  handler satisfies AppPageConfig<"/en/retour-herroepingsrecht">
}

// Validate ..\..\app\en\(pages)\segments\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\segments\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/en/segments/[slug]">
}

// Validate ..\..\app\en\(pages)\segments\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\segments\\page.js")
  handler satisfies AppPageConfig<"/en/segments">
}

// Validate ..\..\app\en\(pages)\services\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\services\\page.js")
  handler satisfies AppPageConfig<"/en/services">
}

// Validate ..\..\app\en\(pages)\shop\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\shop\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/en/shop/[slug]">
}

// Validate ..\..\app\en\(pages)\shop\cart\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\shop\\cart\\page.js")
  handler satisfies AppPageConfig<"/en/shop/cart">
}

// Validate ..\..\app\en\(pages)\shop\checkout\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\shop\\checkout\\page.js")
  handler satisfies AppPageConfig<"/en/shop/checkout">
}

// Validate ..\..\app\en\(pages)\shop\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\shop\\page.js")
  handler satisfies AppPageConfig<"/en/shop">
}

// Validate ..\..\app\en\(pages)\sustainability\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\sustainability\\page.js")
  handler satisfies AppPageConfig<"/en/sustainability">
}

// Validate ..\..\app\en\(pages)\valentijn-3d-printen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\valentijn-3d-printen\\page.js")
  handler satisfies AppPageConfig<"/en/valentijn-3d-printen">
}

// Validate ..\..\app\en\(pages)\viewer\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\viewer\\page.js")
  handler satisfies AppPageConfig<"/en/viewer">
}

// Validate ..\..\app\segments\3d-printing-back-to-school\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-back-to-school\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-back-to-school">
}

// Validate ..\..\app\segments\3d-printing-engineers\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-engineers\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-engineers">
}

// Validate ..\..\app\segments\3d-printing-makers\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-makers\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-makers">
}

// Validate ..\..\app\segments\3d-printing-marketing\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-marketing\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-marketing">
}

// Validate ..\..\app\segments\3d-printing-modelbouwers\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-modelbouwers\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-modelbouwers">
}

// Validate ..\..\app\segments\3d-printing-prototypes\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-prototypes\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-prototypes">
}

// Validate ..\..\app\segments\3d-printing-scholen\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-scholen\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-scholen">
}

// Validate ..\..\app\segments\3d-printing-seasonal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-seasonal\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-seasonal">
}

// Validate ..\..\app\segments\3d-printing-tabletop\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-tabletop\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-tabletop">
}

// Validate ..\..\app\segments\3d-printing-vaderdag-moederdag\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-vaderdag-moederdag\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-vaderdag-moederdag">
}

// Validate ..\..\app\segments\3d-printing-valentijn\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\3d-printing-valentijn\\page.js")
  handler satisfies AppPageConfig<"/segments/3d-printing-valentijn">
}

// Validate ..\..\app\api\contact\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\contact\\route.js")
  handler satisfies RouteHandlerConfig<"/api/contact">
}

// Validate ..\..\app\data\[feed]\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\data\\[feed]\\route.js")
  handler satisfies RouteHandlerConfig<"/data/[feed]">
}

// Validate ..\..\app\en\data\[feed]\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\en\\data\\[feed]\\route.js")
  handler satisfies RouteHandlerConfig<"/en/data/[feed]">
}





// Validate ..\..\app\(home)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(home)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\app\(pages)\blog\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\blog\\layout.js")
  handler satisfies LayoutConfig<"/blog">
}

// Validate ..\..\app\(pages)\crm\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\crm\\layout.js")
  handler satisfies LayoutConfig<"/crm">
}

// Validate ..\..\app\(pages)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\app\(pages)\shop\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(pages)\\shop\\layout.js")
  handler satisfies LayoutConfig<"/shop">
}

// Validate ..\..\app\en\(home)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(home)\\layout.js")
  handler satisfies LayoutConfig<"/en">
}

// Validate ..\..\app\en\(pages)\blog\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\blog\\layout.js")
  handler satisfies LayoutConfig<"/en/blog">
}

// Validate ..\..\app\en\(pages)\shop\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\(pages)\\shop\\layout.js")
  handler satisfies LayoutConfig<"/en/shop">
}

// Validate ..\..\app\en\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\en\\layout.js")
  handler satisfies LayoutConfig<"/en">
}

// Validate ..\..\app\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\app\segments\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\segments\\layout.js")
  handler satisfies LayoutConfig<"/segments">
}
