<?php
declare(strict_types=1);

return [
  [
    "slug" => "bambu-reusable-spool",
    "nameNl" => "Bambu reusable spool",
    "nameEn" => "Bambu reusable spool",
    "summaryNl" => "Originele Bambu reusable spool uit reststock, gecontroleerd en direct klaar voor een refill. EUR 5.00 per stuk, excl. verzending.",
    "summaryEn" => "Original Bambu reusable spool from leftover stock, checked and ready for a refill. EUR 5.00 per item, excl. shipping.",
    "tags" => "bambu, spool, reusable, refill, filament, reststock",
    "priceCents" => 500,
    "availability" => "InStock",
    "stockCount" => 13,
    "purchaseMode" => "inquiry",
    "imageUrl" => "/images/webshop/reusable_spool.png",
    "imageAltNl" => "Bambu reusable spool uit reststock",
    "imageAltEn" => "Bambu reusable spool from leftover stock",
    "leadTimeMin" => 1,
    "leadTimeMax" => 3,
    "isLive" => true,
    "sortOrder" => 10,
  ],
  [
    "slug" => "selectieve-hoornaarval-deksel",
    "nameNl" => "3D geprint deksel voor selectieve hoornaarval",
    "nameEn" => "3D printed lid for selective hornet trap",
    "summaryNl" => "3D geprint deksel voor een selectieve hoornaarval tegen de Aziatische hoornaar. Past op standaard glazen potten en wordt op aanvraag gemaakt voor EUR 4.00 per stuk.",
    "summaryEn" => "3D printed lid for a selective hornet trap aimed at the Asian hornet. Fits standard wide-mouth glass jars and is made to order at EUR 4.00 per piece.",
    "tags" => "hoornaarval, aziatische hoornaar, selectieve val, deksel, petg, outdoor, monitoring",
    "priceCents" => 400,
    "availability" => "PreOrder",
    "stockCount" => null,
    "purchaseMode" => "inquiry",
    "imageUrl" => "/images/webshop/selectieve-hoornaarval-deksel.webp",
    "imageAltNl" => "3D geprint deksel voor selectieve hoornaarval op glazen pot",
    "imageAltEn" => "3D printed lid for a selective hornet trap on a glass jar",
    "leadTimeMin" => 2,
    "leadTimeMax" => 5,
    "isLive" => true,
    "sortOrder" => 20,
  ],
];
