<?php
declare(strict_types=1);

return [
  [
    "slug" => "bambu-reusable-spool",
    "nameNl" => "Bambu reusable spool",
    "nameEn" => "Bambu reusable spool",
    "summaryNl" => "Originele Bambu reusable spool voor filament refills. Momenteel niet op voorraad; je kunt wel een aanvraag achterlaten voor zodra er opnieuw spools beschikbaar zijn.",
    "summaryEn" => "Original Bambu reusable spool for filament refills. Currently out of stock; you can still submit a request for when spools become available again.",
    "tags" => "bambu, spool, reusable, refill, filament, reststock",
    "priceCents" => 500,
    "availability" => "OutOfStock",
    "stockCount" => 0,
    "purchaseMode" => "inquiry",
    "imageUrl" => "/images/webshop/reusable_spool.png",
    "imageAltNl" => "Bambu reusable spool uit reststock",
    "imageAltEn" => "Bambu reusable spool from leftover stock",
    "leadTimeMin" => 1,
    "leadTimeMax" => 3,
    "isLive" => true,
    "sortOrder" => 10,
  ],
  [
    "slug" => "selectieve-hoornaarval-deksel",
    "nameNl" => "Hoornaarval deksel voor selectieve hoornaarvallen",
    "nameEn" => "Selective hornet trap lid for wide-mouth jars",
    "summaryNl" => "Hoornaarval deksel voor selectieve hoornaarvallen tegen de Aziatische hoornaar. 3D geprint in PETG, passend op standaard glazen potten en per stuk of in kleine reeks aan te vragen.",
    "summaryEn" => "Selective hornet trap lid for Asian hornet monitoring. 3D printed in PETG, designed for standard wide-mouth glass jars, and available per piece or in small batches.",
    "tags" => "hoornaarval, aziatische hoornaar, selectieve val, deksel, petg, outdoor, monitoring",
    "priceCents" => 400,
    "availability" => "PreOrder",
    "stockCount" => null,
    "purchaseMode" => "inquiry",
    "imageUrl" => "/images/webshop/hoornaarvallen.jpg",
    "imageAltNl" => "Selectieve hoornaarvallen met 3D geprint deksel voor glazen potten",
    "imageAltEn" => "Selective hornet traps with a 3D printed lid for glass jars",
    "leadTimeMin" => 2,
    "leadTimeMax" => 5,
    "isLive" => true,
    "sortOrder" => 20,
  ],
];
